name = "plans-catalogue"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "plans-catalogue-db"
database_id = "56170a78-267f-480d-b68a-e1471d5fe3e4"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "plans-catalogue-images"
